# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- release

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(solution)'
    vstsFeed: '3b91d9cc-9c4f-4129-88d6-e77bb8a0cb62/6309bacb-dd0d-47a7-ac81-f23a748d0aec'

- task: DotNetCoreCLI@2
  displayName: "Build"
  inputs:
    command: build
    arguments: --configuration Release

- task: DotNetCoreCLI@2
  displayName: "Test Release"
  inputs:
    command: 'test'
    projects: '**/*UnitTests.csproj'
    arguments: --configuration Release

- task: DotNetCoreCLI@2
  displayName: "Publish"
  inputs:
    command: publish 
    arguments: -r win-x64 -p:PublishSingleFile=True --self-contained false -o $(Build.ArtifactStagingDirectory) --configuration Release
    projects: '**/Synthesis.Bethesda.GUI.csproj'
    publishWebProjects: false
  enabled: true

- task: DotNetCoreCLI@2
  displayName: "Pack"
  inputs:
      command: pack

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Synthesis'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()